config/routes.rb
Rails.application.routes.draw do
  resources :peer_reviews

  root 'peer_reviews#index'

end

app/controllers/peer_reviews_controller.rb
class PeerReviewsController < ApplicationController
  before_action :set_peer_review, only: [:show, :edit, :update, :destroy]

  # GET /peer_reviews
  # GET /peer_reviews.json
  def index
    @names = PeerReview.select(:name).group(:name).order('max(year || substr(\'00\' || month, -2, 2)) DESC').order(updated_at: :desc).map(&:name)
    @names_to_reviews = {}
    @names.each do |name|
      @names_to_reviews[name] = PeerReview.where(name: name).order(year: :desc, month: :desc)
    end
  end

  # GET /peer_reviews/1
  # GET /peer_reviews/1.json
  def show
    @parser = PeerReviewParser.new(@peer_review.peer_reviews, @peer_review.self_review)
    @averages = @parser.averages_hash
    @counts = @parser.counts
    @show_overall_section = @counts.values.any?{|h| h.values.any?{|c| c > 0 } }
    @self_review_counts = @parser.self_review_counts
    @text_feedback = @parser.text_feedback
    @self_review_text = @parser.self_review_text
    @previous_peer_review = @peer_review.previous
    @next_peer_review = @peer_review.next
  end

  # GET /peer_reviews/new
  def new
    @peer_review = PeerReview.new
  end

  # GET /peer_reviews/1/edit
  def edit
  end

  # POST /peer_reviews
  # POST /peer_reviews.json
  def create
    @peer_review = PeerReview.new(peer_review_params)

    respond_to do |format|
      if @peer_review.save
        format.html { redirect_to @peer_review, notice: 'Peer review was successfully created.' }
        format.json { render :show, status: :created, location: @peer_review }
      else
        format.html { render :new }
        format.json { render json: @peer_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peer_reviews/1
  # PATCH/PUT /peer_reviews/1.json
  def update
    respond_to do |format|
      if @peer_review.update(peer_review_params)
        format.html { redirect_to @peer_review, notice: 'Peer review was successfully updated.' }
        format.json { render :show, status: :ok, location: @peer_review }
      else
        format.html { render :edit }
        format.json { render json: @peer_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peer_reviews/1
  # DELETE /peer_reviews/1.json
  def destroy
    @peer_review.destroy
    respond_to do |format|
      format.html { redirect_to peer_reviews_url, notice: 'Peer review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peer_review
      @peer_review = PeerReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peer_review_params
      params[:peer_review].permit(:peer_reviews,:self_review,:name,:month,:year,:people_sent)
    end
end

app/helpers/peer_reviews_helper.rb
module PeerReviewsHelper
  HEADER_TO_DESCRIPTION = {
    'Team Player'               => 'Treats teammates with respect.  Solicits and incorporates input from teammates.  Able and willing to compromise position when teammates hold differing position with compelling rationale.',
    'Agile Mindset'             => 'Values incremental release and testing over thorough planning and detailed requirements.  Willing to push forward despite uncertainty.  Willing to adapt to changing requirements as additional information surfaces.',
    'Productivity'              => 'Manages distractions and maintains high level of productivity.  Writes code efficiently to solve real problems.  Strong individual contributor to team projects.',
    'Attention to Code Quality' => 'Values high internal quality of codebase.  Understands fundamentals and application of good architecture.  Advocates clean code to team.  Refactors when needed.',
    'Initiative to Improve'     => 'Actively seeks to identify improvements and innovate.  Explores better ways of solving problems. Included but not limited to areas such as product (product ideas aimed toward increasing value delivered to customer), technology (faster delivery/better performance), and codebase (reducing technical debt, architectural integrity).',
    'Active Participant'        => "Voices opinions about technical and product tradeoffs.  Bases opinions on evidence and experience, not emotions or unsubstantiated opinions of others.  Presents opinions rationally and objectively, being respectful of others' opinions.",
    'Data Driven'               => 'Identifies and implements monitoring of key performance indicators.  Ensures every feature is instrumented and monitored.  Advocates for data-driven decisions over subjectivity.  Advocates and invests in analytics infrastructure.',
    'Communication'             => 'Is able to effectively communicate issues and the current state of projects to peers, cross-teams and upper management (Knows who their audience is and communicates appropriately).',
    'Customer Focus'            => "Prioritizes customer input and validation above opinions.  Analyzes product tradeoffs from customer's perspective.  Actively seeks to minimize customer pain and solve real problems.",
    'Ruby'                      => "Proficient with Ruby.  Understands Ruby syntax, semantics, and core API's.",
    'Rails'                     => "Understands Rails conventions and best practices.  Understands Rails strengths and weaknesses.  Writes code that plays to Rails strengths and avoids weaknesses.",
    'HTML and CSS'              => 'Proficient with HTML and CSS.  Understands fundamentals and implementation details of responsive design.  Understands and uses semantic markup and scalable CSS architecture.',
    'Javascript'                => 'Proficient with javascript.  Understands best practices for structuring javascript code.  Implements efficient code and uses best practices for asynchronous browser loading.',
    'Networking'                => 'Understands networking fundamentals including protocols and common implementations.  Appreciates strengths and weaknesses of different networking technologies.  Applies best practices to use of networking technologies.',
    'Databases'                 => 'Understands schema and table structures, query syntax, foreign key relations, transactions, and best practices for designing both queries and tables.',
    'Tools'                     => 'Proficient with tools such as CI, Rubymine, and Git.  Understands how and when to use tools as well as their limitations.  Advises others about proper use of tools.',
    'Testing Practices'         => 'Knows when to use different types of testing methodologies and what types of tests to write. Writes high-quality tests.  Understands when and how to use mocks, stubs, exemplars, and service objects in test code.',
    'Knowledge of Products'     => 'Understands the breadth and depth of Appfolio products.  Knowledgable about their use as well as implementation.  Understands product roadmaps and major initiatives.',
    'Overall Distribution'      => 'This shows how many attributes were rated at each level across all the questions.'
  }.freeze

  def description_for(header)
    HEADER_TO_DESCRIPTION[header]
  end
end

app/views/peer_reviews/_form.html.erb
<%= form_for(@peer_review) do |f| %>
  <% if @peer_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peer_review.errors.count, "error") %> prohibited this peer_review from being saved:</h2>

      <ul>
      <% @peer_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :people_sent %>
  <%= f.text_area :people_sent, cols: 100, rows: 1 %>
  <br />
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :month %>
  <%= f.text_field :month %>
  <br />
  <%= f.label :year %>
  <%= f.text_field :year %>
  <br />
  <%= f.label :peer_reviews %>
  <%= f.text_area :peer_reviews, cols: 100, rows: 8 %>
  <br />
  <%= f.label :self_review %>
  <%= f.text_area :self_review, cols: 100, rows: 8 %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peer_reviews/_header.html.erb
<% clean_header = header.gsub('[Level]', '').gsub('[Scale]', '').strip %>

<h2><%= clean_header %></h2>
<p><%= description_for(clean_header) %></p>

app/views/peer_reviews/edit.html.erb
<h1>Editing Peer Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @peer_review %> |
<%= link_to 'Back', peer_reviews_path %>

app/views/peer_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Peer Reviews</h1>

<%= link_to 'New Peer review', new_peer_review_path %>
<br>
<br>

<table>
  <% @names.each_with_index do |name, name_index| %>
    <% @names_to_reviews[name].each_with_index do |review, index| %>
      <% label = ((index == 0) ? name : '') %>
      <% if name_index > 0 && index == 0%>
        <tr><td colspan="2"><hr/></td></tr>
      <% end %>
      <tr>
        <td><%= label %></td>
        <td><%= link_to "#{Date::MONTHNAMES[review.month]} #{review.year}", review %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/peer_reviews/new.html.erb
<h1>New Peer Review</h1>

<%= render 'form' %>

<%= link_to 'Back', peer_reviews_path %>

app/views/peer_reviews/show.html.erb
<% content_for :title do %>
  <%= @peer_review.name %>-<%= @peer_review.year %>-<%= @peer_review.month.to_s.rjust(2,'0') %>
<% end %>

<div class="print-hide">
<%= link_to 'Print', '#', onclick: 'window.print()' %> |
<%= link_to 'Edit', edit_peer_review_path(@peer_review) %> |
<%= link_to 'Back', peer_reviews_path %>
<% if @previous_peer_review.present? %>
  | <%= link_to 'Previous Review', @previous_peer_review %>
<% end %>
<% if @next_peer_review.present? %>
  | <%= link_to 'Next Review', @next_peer_review %>
<% end %>
</div>

<div class="show-body">
  <p id="notice"><%= notice %></p>
  <h1><%= @peer_review.name %> - <%= Date::MONTHNAMES[@peer_review.month] %> <%= @peer_review.year %></h1>

  <% if @show_overall_section %>
    <h2>Overall Distribution</h2>
    <p>This shows how many attributes were rated at each level across all the questions.</p>
    <table class="table overall_table">
      <tr>
        <th class="first_column"></th>
        <th>Count</th>
      </tr>
    <% @averages.each do |level, count| %>
      <tr>
        <td><%= level %></td>
        <td><%= "x" * count %></td>
      </tr>
    <% end %>
    </table>
    <hr/>
  <% end %>

  <% i = 0 %>
  <% @counts.each do |header, level_to_count| %>
    <% i += 1 %>
    <%= render partial: 'header', locals: {header: header} %>

    <table class="table details_table">
      <tr>
        <th class="first_column"></th>
        <th>Level</th>
        <th>Improvement</th>
      </tr>
      <% level_to_count.each do |level, count| %>
        <% improvement_hash    = @parser.improvements[header][level] || {} %>
        <% improvement_unknown = improvement_hash['Not Sure'] || 0 %>
        <% improvement_yes     = improvement_hash['Yes'] || 0 %>
        <% improvement_no      = improvement_hash['No'] || 0 %>
        <tr>
          <td><%= level %></td>
          <td><%= 'x' * count %></td>
          <td><%= '+' * improvement_yes %><%= '-' * improvement_no %><%= '?' * improvement_unknown %></td>
        </tr>
      <% end %>
    </table>
    <br/>
    <table class="table summary_table">
      <tr>
        <td class="first_column"><b>Average</b></td>
        <td><%= @parser.average_level(level_to_count)%></td>
      </tr>
      <% if @self_review_counts %>
        <% self_review_value = @self_review_counts[header].select{|k, v| v > 0}.keys.first %>
        <tr>
          <td class="first_column"><b>Self Evaluation</b></td>
          <td><%= self_review_value %></td>
        </tr>
      <% end %>
    </table>

    <% if i % 2 == 0 %>
      <hr class="break"/>
    <% else %>
      <hr/>
    <% end %>
  <% end %>

  <% @text_feedback.each do |header, values| %>
    <h2><%= header %></h2>
    <ul>
    <% values.each do |value| %>
      <li><%= value.html_safe %></li>
    <% end %>
    <% if @self_review_text.present? && @self_review_text[header].present? && @self_review_text[header].first.present? %>
      <li><strong>Self Evaluation:</strong> <%= @self_review_text[header].first %></li>
    <% end %>
    </ul>
    <hr class="break"/>
  <% end %>
</div>